#!/usr/bin/env node

var	argv = require('optimist').argv;
var server = require('./serve.js');

var port = argv.p;
var address = argv.a;

server();

// if (!argv.p) {
// 	server(null, argv.a);
// } else {
// 	server(port);
// }
